server:
  port: 8050
spring:
  application:
    name: gateway-zuul
eureka:
  client:
    serviceUrl:
      defaultZone: http://user:password123@localhost:8761/eureka
zuul:
  ignoredServices: '*'
  routes:
    app-consumer-feign-hystrix:
      path: /user/**
      serviceId: consumer-feign-hystrix
    app-sidecar:
      path: /sidecar/**
      serviceId: sidecar
    

